タスクグループを取得する API の実装
commew/timelogger-api pull request #50
Opened 2023-08-02 13:47 UTC by HaruyaFujimoto

close #42

## この PR の経緯

#46 にて、なぜか 14 commit しか反映されなかったので PR を立て直しました。
立て直している時点ではこの PR では 19 commit の差分があることを確認しています。

## この PR 対応したこと

- [x] task_groups のテーブル定義
- [x] task_categories のテーブル定義
- [x] TaskGroup モデルにて、自身の生成時に TaskCategory も作成される処理を記述
- [x] TaskCategory にて、親となる TaskGroup の削除時に自動削除されることのテストを記述
- [x] コントローラの定義
- [x] リクエストに含まれるアカウント情報に紐づく TaskGroup を返す処理を記述
(TaskCategory をネストに持つ
- [ ] ~~リクエストに対する例外処理を記述~~ (異常系は別 issue で対応予定)

長いので要するに、 `GET /task-groups` が役に立つ状態になっていること。

## この PR で未対応のもの

- リクエスト元の account の特定
jwt 検証による account の authorization 機能は別 issue での対応範囲となっています。
そのため仮として `Account.first || Account.new` のような処理で account を取り出しています。
それで取れた account をアクセス者として扱い、それに紐づく TaskGroups を
JSON 形式で返しています。

- 異常系の処理
このエンドポイントでの異常系は 401, 500 となっています。
401 は authorization にてレスポンスが返される認識で、
500 も別 issue で扱う予定となっています。
そのため、このエンドポイントのテストでは正常系のみテストを記述しています。

## レビュワーに見て欲しいところ

モデル内の記述、FactoryBot の定義、各テストファイルなど、
全体的に処理・文法等についてつっこみどころがあればご指摘いただきたいです。
よろしくお願いいたします！

2023-08-03 00:27 UTC, HaruyaFujimoto commented
1点、controller のテストの記述で悩んだところがありました。

[545f5cc](https://github.com/commew/timelogger-api/pull/50/commits/545f5ccc75f9aee8b39c6fba75d9739725ddda85)
こちらのコミットで response.body の検証方法を変更したのですが、
変更後は controller に **"実装しているロジックと同じ記述"** でテスト結果を生成しています。

変更前のやり方はテストコードの可読性が悪いかと思い、
as_json がエンドポイント定義で決められている形を返すかは
他のモデルでのテストで解決すればいいかと考えました。
ですが、未だにどっちがよかったのだろうか？という気持ちもあります。

これについてご意見をもらえるとうれしいです！

2023-08-05 10:39 UTC, HAYASHI-Masayuki commented on app/models/task_category.rb
> +  end
`TaskGroup`側の`as_json`で指定してるのでこれなくても大丈夫そうです。

2023-08-06 06:25 UTC, stkzk3110 commented on app/controllers/task_groups_controller.rb
> +    account = Account.first || FactoryBot.create(:account)
![badge](https://img.shields.io/badge/review-nits-green.svg)

仮と記載があるので多分問題ないと思いますが、FactoryBotはあくまでテストコードのテストデータ生成のためのものなので本コードで登場することは基本的にないですね。

2023-08-06 07:54 UTC, stkzk3110 commented on app/controllers/task_groups_controller.rb
> +    account = Account.first || FactoryBot.create(:account)
![badge](https://img.shields.io/badge/review-nits-green.svg)

仮と記載があるので多分認識あると思いますが念の為、コメント残しておきます🙏
FactoryBotはあくまでテストコードのテストデータ生成のためのものなので本コードで登場することは基本的にないのでもし本コードでやるなら以下とかですかね🧐

```suggestion
    account = Account.first || Account.create
```

2023-08-06 07:58 UTC, stkzk3110 commented on app/models/account.rb
> +  after_create :create_task_groups
![badge](https://img.shields.io/badge/review-imo-orange.svg)
accountが作られた時にtask_groupsもデフォルトで作成されるということですよね？

ActiveRecordのコールバックって結構Railsエンジニアの中でも避けられるのであれば避けた方が良いという共通認識はあるので、この処理自体をどちらかというとaccount作成動線で処理する形に持っていくのが良いかと思いました。

参考：
https://techracho.bpsinc.jp/hachi8833/2022_09_27/59155

2023-08-06 08:00 UTC, stkzk3110 commented on app/models/task_group.rb
> +  INIT_DATA = {
![badge](https://img.shields.io/badge/review-suggestion-blue.svg)
hashなのでhashって語尾につけてあげても良いかもです。
基本定数って文字列、配列、ハッシュの3パターンが考えられるので配列ならarray、ハッシュならhashってつけ毛あげればその定数の型が読み取れるのでおすすめです。

```suggestion
  INIT_DATA_HASH = {
```

2023-08-07 11:26 UTC, HAYASHI-Masayuki requested changes
タスクグループ・カテゴリの初期値作成回りだけ再検討お願いします。
ほかは問題なさそうです！

2023-08-07 11:26 UTC, HAYASHI-Masayuki commented on app/models/account.rb
> +  def create_task_groups
ここは単に作るというよりは初期化してるところだと思うので、メソッド名は`init~`とかの方が合ってるかもしれません。

2023-08-07 11:26 UTC, HAYASHI-Masayuki commented on app/models/task_group.rb
> +  after_create :create_categories
タスクグループ作成時にフックでタスクカテゴリを作成することで、初期化を実現されているんですね。
このやり方だと、以下のような挙動になってしまうのが気になりました。
1. 現状やっていないですが、`TaskGroup.create`時にデフォルト値が存在しない名前(たとえば`'test'`)を指定すると落ちる。
2. 同じく`TaskGroup.create`時にデフォルト値が存在「する」名前を指定した場合は今度は同じ名前のグループと、その下にデフォルト値のタスクカテゴリができてしまう。

そもそも同じ名前のグループやカテゴリについて、設計の時点で考慮漏れてましたね……。

フックを使って再帰的にデフォルト値を組み立てる方法はスマートですが、ちょっと余計な挙動が多くなるので、ここは泥臭く一括で作っちゃう感じでもいいかなと思います。`TaskGroup`の静的メソッド(Rubyだとなんか別の名前だった気が)とかで。

2023-08-07 11:33 UTC, HAYASHI-Masayuki commented
> 545f5cc
> こちらのコミットで response.body の検証方法を変更したのですが、
> 変更後は controller に "実装しているロジックと同じ記述" でテスト結果を生成しています。
> 
> 変更前のやり方はテストコードの可読性が悪いかと思い、
> as_json がエンドポイント定義で決められている形を返すかは
> 他のモデルでのテストで解決すればいいかと考えました。
> ですが、未だにどっちがよかったのだろうか？という気持ちもあります。

わかります。いくら自動テストではデータは素朴に書いてわかりやすく～とは言っても限度ありますもんね。
で、仰る通り`as_json`が適切なデータを返すかはモデル側のテストで保証されてるので、コントローラ側では、`as_json`がそのまま返って来ることをテストする、でぜんぜんいいんじゃないかと思います。

2023-08-07 11:50 UTC, HaruyaFujimoto commented on app/models/task_category.rb
> +  end
こちらその通りでした。
もしかしたら TaskCategory 単体で取得するケースもあるかもな？と思って記述した気がするのですが、
現状の仕様では不要なメソッドです。
変更しておこうと思います。

2023-08-07 12:05 UTC, HaruyaFujimoto commented on app/models/account.rb
> +  after_create :create_task_groups
> ActiveRecordのコールバックって結構Railsエンジニアの中でも避けられるのであれば避けた方が良いという共通認識はあるので

そうなんですね、こういった情報を教えていただけると大変嬉しいです！
むしろ Rails 標準機能は積極的に使ったほうがいいのかなと思っていました。
ここ含めて、コールバックは使わないようにしたいと思います。
参考の URL もありがとうございます！🙌

2023-08-07 12:10 UTC, HaruyaFujimoto commented on app/models/task_group.rb
> +  INIT_DATA = {
ご指摘ありがとうございます。

> 基本定数って文字列、配列、ハッシュの3パターンが考えられるので

こちらのご説明で Ruby の定数においては、接尾辞に型を書いておくことの有効性が高そうだと感じました。
今後の考え方としても参考にさせていただきます💪

2023-08-12 08:46 UTC, HaruyaFujimoto commented on app/models/task_group.rb
> +  after_create :create_categories
きゅーぶさんのご指摘でも ActiveRecord のコールバックは避けた方がよいとのことでしたので、
コールバックの連鎖のような現状の実装をやめて、一つの関数内で
TaskGroup, TaskCategory どちらもインスタンス生成するようにしたいと考えています。
https://github.com/commew/timelogger-api/pull/50#discussion_r1285171312
修正後、またこちらにコメントをしようと思います。

2023-08-12 09:34 UTC, HaruyaFujimoto commented on app/models/task_group.rb
> +  after_create :create_categories
[596f6d6](https://github.com/commew/timelogger-api/pull/50/commits/596f6d64f93dad221f7b69dda8db1dff00966ced)
こちらのコミットにて対応いたしました！

一つの関数内で TaskGroup::INIT_DATA_HASH の形状で task_group, task_category が
作成されるようにしてみました。
その一つの関数というのが、Account.create_with_open_id_provider からのみ実行される
というのが守られる前提ですが、ひとまずご指摘の点には対応できたのではないかと思っております。

2023-08-12 09:37 UTC, HaruyaFujimoto commented
@HAYASHI-Masayuki 
レビューでご指摘いただいていいた点に対応し、他に以下の変更を加えました。
再度ご確認をお願いできますでしょうか？

- controller にて `@account` から task_groups を取得するように変更 (以前は仮の実装だった)
- Accout.create_with_open_id_provider の処理の中に、初期のタスクグループ作成処理を追加した
- ActiveRecord のコールバック削除にあたり、factory まわりの変更

2023-08-12 10:58 UTC, HAYASHI-Masayuki approved these changes
LGTM! 細かいコメントは入れましたが基本問題なさそうです！

2023-08-12 10:58 UTC, HAYASHI-Masayuki commented on app/models/task_group.rb
> +      task_group
ここ私ならこんな風に書きます。
`TaskGroup`と`TaskCategory`をそれぞれ`map`して`new`して～とできて読みやすいと思うので。

```suggestion
      TaskGroup.new(name: task_group_name).tap do |task_group|
        task_group.categories << INIT_DATA_HASH[task_group_name].map do |task_category_name|
          TaskCategory.new(name: task_category_name)
        end
      end
```

2023-08-12 10:58 UTC, HAYASHI-Masayuki commented on spec/models/task_group_spec.rb
> +  describe '.init_default_tasks' do
現状だとここで、タスクグループ内のタスクカテゴリの作成までは十分にテストできてないのでもうちょっとテストあってもいいかもしれません。
`init_default_tasks`内でタスクカテゴリが適切な名前で作成できなくても、落ちるテストが今のところまったくなさそうなんですよね。

2023-08-13 09:19 UTC, HaruyaFujimoto commented on spec/models/task_group_spec.rb
> +  describe '.init_default_tasks' do
全くその通りで、以下でテストを追加しました。
[855aabd](https://github.com/commew/timelogger-api/pull/50/commits/855aabd8570144b57beccf611481409f0a2cbd8e)

テストを追加したところ、実装をミスっていたのに気付き、そちらの修正も行いました。
(`task_category.name = {name: 'カテゴリ名'}` という実装になっていました、やっぱりテスト大事です。。)


またこちらのコミットにて task_groups の eager_load も追加しています。
林さんに教えていただいた方法にプラスして、order も指定するように調整しました。

これは何度か自動テストにて、task_groups の順番が変わって失敗する、ということが起こっていたため
order を入れておいた方がよさそうだと思い、そのようにしました。

こちらのコミットの内容のご確認をお願いできますでしょうか？
問題なさそうであればマージをお願いできればと思っています。

2023-08-14 08:53 UTC, HAYASHI-Masayuki commented
@HaruyaFujimoto 追加修正分確認しました、問題なさそうです！　ありがとうございました。

2023-08-14 08:53 UTC, merged