WIP: Task の記録開始のエンドポイントの実装
commew/timelogger-api pull request #65
Opened 2023-09-09 10:25 UTC by HaruyaFujimoto

## 現状

- エンドポイントの実装のまえに、タスクのステータスを変更する3種類のエンドポイントで
共通利用することになりそうなメソッドをモデルで定義した。
- raiils console で動作確認はしたが、テストコードは書く場所だけ用意して未実装。

2023-09-09 10:38 UTC, HAYASHI-Masayuki commented on app/models/task.rb
> +    end
`each`じゃなくて`sum`だと、初期化や戻り値の指定の2行いらなくなる気がします！

2023-09-09 11:37 UTC, HaruyaFujimoto commented on app/models/task.rb
> +    end
ご指摘ありがとうございます！
こちらそのように変更しました！

2023-09-10 04:29 UTC, HAYASHI-Masayuki requested changes
いくつか気になる点あったので、ご確認お願いします:pray:

2023-09-10 04:29 UTC, HAYASHI-Masayuki commented on app/models/task.rb
> +    return :recording if task_time_units.last.end_at.nil?
`end_at.nil?`だけでよさそうです。

2023-09-10 04:29 UTC, HAYASHI-Masayuki commented on app/models/task.rb
> +  end
`task.`あるとエラーになる気がします。

2023-09-10 04:29 UTC, HAYASHI-Masayuki commented on app/models/task.rb
> +    raise 'Task is already stoped.' unless status == :recording
細かいところですがエラーメッセージ、`stoped`になってますね。

2023-09-10 04:29 UTC, HAYASHI-Masayuki commented on app/models/task.rb
> +    latest_time_unit.end_at = end_at if latest_time_unit.end_at.nil?
ここ常に`latest_time_unit.end_at = end_at`してもいいんじゃないかなー、と思いましたが、記録中に終了するパターンだけでなく、停止中に終了するパターンもありうるので、その場合はこれが必要なんですね、なるほど。
ちょっとややこしくて混乱します、むずかしい……。

2023-09-10 09:53 UTC, HaruyaFujimoto commented on app/models/task.rb
> +    latest_time_unit.end_at = end_at if latest_time_unit.end_at.nil?
そうですね、ここのロジックはもしかしたらもう少し書きようがあるかもしれません。
今のところ挙動としては間違っていないと思うので、いい方法が思いついたらリファクタしていくでよいのかなと思っています。

2023-09-10 09:54 UTC, HaruyaFujimoto commented on app/models/task.rb
> +    return :recording if task_time_units.last.end_at.nil?
ご指摘の通りでしたので、そのように変更をいたしました。

2023-09-10 09:55 UTC, HaruyaFujimoto commented on app/models/task.rb
> +  end
ご指摘の通りです！
修正してテストも追加したのでご確認いただければと思います。

2023-09-10 09:56 UTC, HaruyaFujimoto commented on app/models/task.rb
> +    raise 'Task is already stoped.' unless status == :recording
このメソッドだけでなく、ステータス更新系のメソッドについてエラーメッセージを変更いたしました。
ご確認をお願いできればと思います。

2023-09-10 09:57 UTC, HaruyaFujimoto commented on app/models/task.rb
> +  }.freeze
Task の状態を表す方法について、クラス定数を用意してそれを呼ぶように変更しました。

2023-09-10 10:02 UTC, HaruyaFujimoto commented on app/models/task.rb
> +    raise "Task status is #{current_status}, could not make status pending." unless current_status == STATUS[:recording]
この `current_status` ですが、status メソッドを unless の式と raise に渡す文字列への埋め込みに書くと
2回DB問い合わせが起こったため、一度変数に受けるようにしています。

2023-09-10 10:05 UTC, HaruyaFujimoto commented
@HAYASHI-Masayuki 
レビューありがとうございました！
突貫でテストなしで書いていたところでだいぶザルになっていました。

書くメソッドについてテストも用意いたしましたので、ご指摘いただいた点への対応と
追加したテストについて再度レビューをお願いできればと思います。

よろしくお願いいたします！

2023-09-10 10:51 UTC, HAYASHI-Masayuki approved these changes
LGTM! 修正ありがとうございました！

2023-09-10 10:51 UTC, HAYASHI-Masayuki commented on app/models/task.rb
> +    raise "Task status is #{current_status}, could not make status pending." unless current_status == STATUS[:recording]
なるほど……。`sefl.task_time_units`ってキャッシュされないんですかね。Laravelだとキャッシュされるのでびっくりです。

2023-09-10 10:51 UTC, merged