記録中のタスク一覧を取得するAPIを実装した
commew/timelogger-api pull request #66
Opened 2023-09-16 07:20 UTC by HAYASHI-Masayuki

Closes #44 

ついでに(本当は別にした方がいいんですが)eager loadingになっていないかのチェックのために[Bullet](https://github.com/flyerhzm/bullet)というGemを入れてみました。

それはともかく、ファクトリの変更などもあり、`dev`をマージした上でのテストは一通り通ってはいるものの、ほかへの影響がないかも見ていただけると助かります。

2023-09-16 07:24 UTC, HAYASHI-Masayuki commented on config/environments/development.rb
> +  config.after_initialize do
コミットに書き忘れたのでこちらに。Bulletの設定は、`rails g bullet:install`して(その後出るテスト環境でも有効するかの質問にはYesと答えて)自動生成したもの、そのまま。

2023-09-16 07:29 UTC, HAYASHI-Masayuki commented on spec/factories/accounts.rb
> +    end
一部、以前のように`sub`が`111111111111111111111`のOpenIdProviderを作りたかったためこうした。が、今思えばテストの方を修正してもよかったかも。

2023-09-16 07:31 UTC, HAYASHI-Masayuki commented on app/controllers/tasks_controller.rb
> +    render_tasks Task.preload(:task_time_units).where(id: task_ids)
LaravelのEloquentでは、取得したモデルのコレクションに対して`load`というメソッドを使用して、関連するモデルを後から一括で読み込むことができるが、ActiveRecordではできないようで、一旦IDだけ取得した上で`preload`する形で対応。

2023-09-16 10:21 UTC, HAYASHI-Masayuki commented on app/controllers/tasks_controller.rb
> +    task_ids = Task
ふじもとさんからご指摘: アカウント見てない。確かに。要修正！

2023-09-16 10:23 UTC, HAYASHI-Masayuki commented on app/controllers/tasks_controller.rb
> +      endAt: task.end_at&.rfc3339,
`endAt`は`null`を返さないはず。requiredなので、`null`の場合は、`0000-00-00T00:00:00Z`を返すべきのはず。

2023-09-16 10:25 UTC, HAYASHI-Masayuki commented on app/controllers/tasks_controller.rb
> +    task_ids = Task
そもそも`skip_before_action :authenticate`しちゃってるので、そこ削除して、その上でテスト通るようにするところから。

2023-09-16 10:26 UTC, HAYASHI-Masayuki commented on app/controllers/tasks_controller.rb
> +      endAt: task.end_at&.rfc3339,
`start_at`がnullの場合はありえないのでは？　そちらも要確認・必要に応じて修正。

2023-09-16 10:41 UTC, HaruyaFujimoto commented on spec/requests/tasks_spec.rb
controller にて認証を動かすにあたり、5行目のような未実装のパスへのテストにつきまして、
以下のように記述を変更していただき、テストケースをスキップするよう変更をお願いできればと思います。
```
describe 'POST /tasks', skip: '未実装のためスキップ' do
```

2023-09-23 08:23 UTC, HAYASHI-Masayuki commented
@HaruyaFujimoto 一通り修正しました！　追加部分レビューお願いします。
停止中タスクの方 #67 も修正済みです。

2023-10-03 08:45 UTC, HaruyaFujimoto requested changes
レビューでコメントを追加させていただきましたのでご確認をお願いいたします！

2023-10-03 08:45 UTC, HaruyaFujimoto commented on app/controllers/tasks_controller.rb
> +      taskCategoryId: task.task_category.task_group.id
```suggestion
      taskGroupId: task.task_category.task_group.id,
      taskCategoryId: task.task_category.id
```
キーと値が一致していないような気がしました。
正しそうか確認をお願いできればと思います。

2023-10-03 08:45 UTC, HaruyaFujimoto commented on spec/requests/tasks_spec.rb
> +      end
コントローラーでの指摘とあわせて、json のキーと値の指定が正しそうか、ご確認をお願いいたします。

2023-10-03 08:45 UTC, HaruyaFujimoto commented on spec/support/test_helpers.rb
このヘルパーは使い勝手がよさそうです！！

2023-10-03 23:51 UTC, HAYASHI-Masayuki commented on app/controllers/tasks_controller.rb
> +      taskCategoryId: task.task_category.task_group.id
Oh... なんでこんなことに。
ありがとうございます。ほかにもあるかもなので一通り見てみます！

2023-10-05 06:45 UTC, HAYASHI-Masayuki commented
@HaruyaFujimoto レビューありがとうございました！
ご指摘いただいたバグ、もう片方のPRも含め修正しましたので、お手数ですがそこだけ再度レビューお願いします。

2023-10-06 03:47 UTC, HaruyaFujimoto approved these changes
LGTM です！
rspec でレスポンスボディを出力してみたりもしましたが、良さそうです！

2023-10-06 08:43 UTC, merged