停止中のタスク一覧を取得するAPIを実装した
commew/timelogger-api pull request #67
Opened 2023-09-16 08:10 UTC by HAYASHI-Masayuki

Closes #45

記録中タスク一覧API実装のブランチから切ってます。

2023-09-16 08:15 UTC, HAYASHI-Masayuki commented on app/controllers/tasks_controller.rb
> +               .group('tasks.id')
GROUP BYではモデルのテーブル以外で絞り込むこともあるから`group`ではテーブル名で修飾して指定、`where`でモデルのテーブル以外で絞り込む場合は基本`merge`か`where(task_time_units: { ... })`の形にするから、こちらは常にモデルのテーブル想定、ということでハッシュで渡しています。

内部的にも、`joins`していてテーブル名で修飾されていない`where`のキーは、モデルのテーブル名で修飾されているようなので大丈夫だと思いますが、もし勘違いしていましたらご指摘ください。

↑↑の考え方の違和感とかも。

2023-10-04 04:06 UTC, HaruyaFujimoto requested changes
#66 で指摘済みの部分以外はよさそうです！

2023-10-04 04:06 UTC, HaruyaFujimoto commented on spec/requests/tasks_spec.rb
> +      end
#66 でのレビューと同じく、json のキーと値の組み合わせが違っているような気がします。

2023-10-04 04:09 UTC, HaruyaFujimoto commented on app/controllers/tasks_controller.rb
> +               .group('tasks.id')
こちら問題ないと思います！

2023-10-06 03:51 UTC, HaruyaFujimoto approved these changes
LGTM です！問題ないと思います！

2023-10-06 08:43 UTC, merged